# Generated by Django 4.0.4 on 2022-05-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine_Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='accion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='aventura',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='comedia',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='suspenso',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='terror',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='thriller',
        ),
        migrations.AddField(
            model_name='categoria',
            name='n_categoria',
            field=models.CharField(default=1, max_length=50, verbose_name='nombre de categoria'),
            preserve_default=False,
        ),
    ]
