# Generated by Django 4.0.4 on 2022-05-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine_Blog', '0002_remove_categoria_accion_remove_categoria_aventura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.CharField(max_length=600, verbose_name='sinopsis'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('n_categoria',)},
        ),
        migrations.AlterUniqueTogether(
            name='pelicula',
            unique_together={('titulo',)},
        ),
    ]
