# Generated by Django 4.0.4 on 2022-05-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCine_Blog', '0004_alter_pelicula_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/media'),
        ),
    ]
